### ISSUE TITLE
Would you accept PR for downloading from private repositories?

### ISSUE THREAD

**Issue by StevenACoffman** [axllent/ghru#1]
This is an incredibly useful tool! I wondered if you would be open to a pull request, such that if there was an environment variable (`GITHUB_AUTH_TOKEN`) it would use a personal access token for both the API call and to enable downloading releases from private repositories?

---

To download release file from private repo, you can use Personal access token which can be generated at [settings/tokens][1] with *Full control of private repositories* scope.

Then download the asset with `curl` command (change with appropriate values):

    curl -vLJO -H 'Authorization: token my_access_token' 'https://api.github.com/repos/:owner/:repo/releases/assets/:id'

or if you're using an OAuth app, use:

    curl -u my_client_id:my_client_secret https://api.github.com/repos/:owner/:repo/releases/assets/:id

where:

- `:owner` is your user or organisation username;
- `:repo` is your repository name;
- `:id` is your asset id, can be found in tag release URL, like:

        https://api.github.com/repos/:owner/:repo/releases/tags/:tag 

- `:token` is your personal access token (can be created at `/settings/tokens`;

Note: Using `access_token` as a query param is [deprecated](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/#changes-to-make).

See: [Repositories API v3 at GitHub][2]

----------

  [1]: https://github.com/settings/tokens
  [2]: https://developer.github.com/v3/repos/

**Comment by axllent** [comment]
@StevenACoffman I'm so sorry, for reasons I cannot explain I completely overlooked (didn't see) your message?!

Thanks for the compliment! Yes I'm totally open to a PR. I assume that private repos would be a use-case for a company's internal software or something, am I right? I've been intending to write an alternative to this module that offers more flexibility (such as naming conventions and/or archive format), but to be honest I've just not had the time or motivation. This works well for what I need / use.

I'd say that the best approach for what you are needing would be an optional method in ghru to optionally provide OAuth credentials, and just forget about the deprecated method - I don't see any reason to provide support for something that is going to be phased out. Whether your app uses an environment variable, or a hard-coded (either in the source code, set or at build time) is entirely up to the software developer I guess. Does that make sense to you?
